// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLModel
{
    public class ModelInput
    {
        [ColumnName("riqi"), LoadColumn(0)]
        public string Riqi { get; set; }

        [ColumnName("spj"), LoadColumn(1)]
        public float Spj { get; set; }


        [ColumnName("zgj"), LoadColumn(2)]
        public float Zgj { get; set; }


        [ColumnName("zdj"), LoadColumn(3)]
        public float Zdj { get; set; }


        [ColumnName("kpj"), LoadColumn(4)]
        public float Kpj { get; set; }


        [ColumnName("qsp"), LoadColumn(5)]
        public float Qsp { get; set; }


        [ColumnName("zdf"), LoadColumn(6)]
        public string Zdf { get; set; }


        [ColumnName("hsl"), LoadColumn(7)]
        public float Hsl { get; set; }


        [ColumnName("cjl"), LoadColumn(8)]
        public float Cjl { get; set; }


        [ColumnName("cjje"), LoadColumn(9)]
        public float Cjje { get; set; }


        [ColumnName("zsz"), LoadColumn(10)]
        public float Zsz { get; set; }


        [ColumnName("ltsz"), LoadColumn(11)]
        public float Ltsz { get; set; }


        [ColumnName("spj0"), LoadColumn(12)]
        public float Spj0 { get; set; }


        [ColumnName("spj1"), LoadColumn(13)]
        public float Spj1 { get; set; }


        [ColumnName("spj2"), LoadColumn(14)]
        public float Spj2 { get; set; }


        [ColumnName("spj3"), LoadColumn(15)]
        public float Spj3 { get; set; }


        [ColumnName("spj4"), LoadColumn(16)]
        public float Spj4 { get; set; }


        [ColumnName("zgj0"), LoadColumn(17)]
        public float Zgj0 { get; set; }


        [ColumnName("zgj1"), LoadColumn(18)]
        public float Zgj1 { get; set; }


        [ColumnName("zgj2"), LoadColumn(19)]
        public float Zgj2 { get; set; }


        [ColumnName("zgj3"), LoadColumn(20)]
        public float Zgj3 { get; set; }


        [ColumnName("zgj4"), LoadColumn(21)]
        public float Zgj4 { get; set; }


        [ColumnName("zdj0"), LoadColumn(22)]
        public float Zdj0 { get; set; }


        [ColumnName("zdj1"), LoadColumn(23)]
        public float Zdj1 { get; set; }


        [ColumnName("zdj2"), LoadColumn(24)]
        public float Zdj2 { get; set; }


        [ColumnName("zdj3"), LoadColumn(25)]
        public float Zdj3 { get; set; }


        [ColumnName("zdj4"), LoadColumn(26)]
        public float Zdj4 { get; set; }


        [ColumnName("kpj0"), LoadColumn(27)]
        public float Kpj0 { get; set; }


        [ColumnName("kpj1"), LoadColumn(28)]
        public float Kpj1 { get; set; }


        [ColumnName("kpj2"), LoadColumn(29)]
        public float Kpj2 { get; set; }


        [ColumnName("kpj3"), LoadColumn(30)]
        public float Kpj3 { get; set; }


        [ColumnName("kpj4"), LoadColumn(31)]
        public float Kpj4 { get; set; }


        [ColumnName("qsp0"), LoadColumn(32)]
        public float Qsp0 { get; set; }


        [ColumnName("qsp1"), LoadColumn(33)]
        public float Qsp1 { get; set; }


        [ColumnName("qsp2"), LoadColumn(34)]
        public float Qsp2 { get; set; }


        [ColumnName("qsp3"), LoadColumn(35)]
        public float Qsp3 { get; set; }


        [ColumnName("qsp4"), LoadColumn(36)]
        public float Qsp4 { get; set; }


        [ColumnName("zdf0"), LoadColumn(37)]
        public string Zdf0 { get; set; }


        [ColumnName("zdf1"), LoadColumn(38)]
        public string Zdf1 { get; set; }


        [ColumnName("zdf2"), LoadColumn(39)]
        public string Zdf2 { get; set; }


        [ColumnName("zdf3"), LoadColumn(40)]
        public string Zdf3 { get; set; }


        [ColumnName("zdf4"), LoadColumn(41)]
        public string Zdf4 { get; set; }


        [ColumnName("hsl0"), LoadColumn(42)]
        public float Hsl0 { get; set; }


        [ColumnName("hsl1"), LoadColumn(43)]
        public float Hsl1 { get; set; }


        [ColumnName("hsl2"), LoadColumn(44)]
        public float Hsl2 { get; set; }


        [ColumnName("hsl3"), LoadColumn(45)]
        public float Hsl3 { get; set; }


        [ColumnName("hsl4"), LoadColumn(46)]
        public float Hsl4 { get; set; }


        [ColumnName("cjl0"), LoadColumn(47)]
        public float Cjl0 { get; set; }


        [ColumnName("cjl1"), LoadColumn(48)]
        public float Cjl1 { get; set; }


        [ColumnName("cjl2"), LoadColumn(49)]
        public float Cjl2 { get; set; }


        [ColumnName("cjl3"), LoadColumn(50)]
        public float Cjl3 { get; set; }


        [ColumnName("cjl4"), LoadColumn(51)]
        public float Cjl4 { get; set; }


        [ColumnName("cjje0"), LoadColumn(52)]
        public float Cjje0 { get; set; }


        [ColumnName("cjje1"), LoadColumn(53)]
        public float Cjje1 { get; set; }


        [ColumnName("cjje2"), LoadColumn(54)]
        public float Cjje2 { get; set; }


        [ColumnName("cjje3"), LoadColumn(55)]
        public float Cjje3 { get; set; }


        [ColumnName("cjje4"), LoadColumn(56)]
        public float Cjje4 { get; set; }


        [ColumnName("zsz0"), LoadColumn(57)]
        public float Zsz0 { get; set; }


        [ColumnName("zsz1"), LoadColumn(58)]
        public float Zsz1 { get; set; }


        [ColumnName("zsz2"), LoadColumn(59)]
        public float Zsz2 { get; set; }


        [ColumnName("zsz3"), LoadColumn(60)]
        public float Zsz3 { get; set; }


        [ColumnName("zsz4"), LoadColumn(61)]
        public float Zsz4 { get; set; }


        [ColumnName("ltsz0"), LoadColumn(62)]
        public float Ltsz0 { get; set; }


        [ColumnName("ltsz1"), LoadColumn(63)]
        public float Ltsz1 { get; set; }


        [ColumnName("ltsz2"), LoadColumn(64)]
        public float Ltsz2 { get; set; }


        [ColumnName("ltsz3"), LoadColumn(65)]
        public float Ltsz3 { get; set; }


        [ColumnName("ltsz4"), LoadColumn(66)]
        public float Ltsz4 { get; set; }


        [ColumnName("mspj"), LoadColumn(67)]
        public float Mspj { get; set; }


    }
}
