// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLModel
{
    public class ModelInput
    {
        [ColumnName("riqi"), LoadColumn(0)]
        public string Riqi { get; set; }


        [ColumnName("gpdm"), LoadColumn(1)]
        public string Gpdm { get; set; }


        [ColumnName("mc"), LoadColumn(2)]
        public string Mc { get; set; }


        [ColumnName("spj"), LoadColumn(3)]
        public float Spj { get; set; }


        [ColumnName("zgj"), LoadColumn(4)]
        public float Zgj { get; set; }


        [ColumnName("zdj"), LoadColumn(5)]
        public float Zdj { get; set; }


        [ColumnName("kpj"), LoadColumn(6)]
        public float Kpj { get; set; }


        [ColumnName("qsp"), LoadColumn(7)]
        public float Qsp { get; set; }


        [ColumnName("zdf"), LoadColumn(8)]
        public string Zdf { get; set; }


        [ColumnName("hsl"), LoadColumn(9)]
        public float Hsl { get; set; }


        [ColumnName("cjl"), LoadColumn(10)]
        public float Cjl { get; set; }


        [ColumnName("cjje"), LoadColumn(11)]
        public float Cjje { get; set; }


        [ColumnName("zsz"), LoadColumn(12)]
        public float Zsz { get; set; }


        [ColumnName("ltsz"), LoadColumn(13)]
        public float Ltsz { get; set; }

        [ColumnName("mspj"), LoadColumn(14)]
        public float Mspj { get; set; }
    }
}
